# Generated by Django 4.1.7 on 2023-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_unit_amount_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_amount',
            field=models.FloatField(),
        ),
    ]
