# Generated by Django 4.1.7 on 2023-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_product_normal_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='food_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_name',
        ),
        migrations.AddField(
            model_name='product',
            name='animal',
            field=models.CharField(default='hond', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='droogvoer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(default='petsplace', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=150),
        ),
    ]
