# Generated by Django 4.1.7 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_date_posted_product_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
