# Generated by Django 4.1.7 on 2023-03-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/testimages.jpg', upload_to='house_pics'),
        ),
    ]
