# Generated by Django 4.1.7 on 2023-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/testlogo.png', upload_to='products'),
        ),
    ]
