# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_product_img.jpg', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(),
        ),
    ]
