# Generated by Django 4.1.7 on 2023-04-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_product_image_alter_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_amount',
        ),
    ]
